version: '3'
services:
  rbc:
    build:
      context: ./rbc
    ports:
      - "8060:8060"
    depends_on:
      - dbpostgresql
  weather:
    build:
      context: ./weather
      dockerfile: Dockerfile
    ports:
      - "8070:8070"  
  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: adminadmin
      POSTGRES_PASSWORD: pwdpwd
