version: '3'
services:
  rbc:
    image: docker-rbc
    build:
      context: ./rbc
    ports:
      - "8060:8060"
    depends_on:
      - dbpostgresql
  weather:
    image: docker-weather
    build:
      context: ./weather
      dockerfile: Dockerfile
    ports:
      - "8070:8070"  
  ml:
    image: docker-ml
    build:
      context: ./ml
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: adminadmin
      POSTGRES_PASSWORD: pwdpwd
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: helena557@mail.ru
      PGADMIN_DEFAULT_PASSWORD: pwdpwd
    depends_on:
      - dbpostgresql
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
