global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'weather_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.56.1:8070']
  - job_name: 'rbc_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.56.1:8060']
  - job_name: 'ml_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.56.1:8050']
